name = "PPInterpolation"
uuid = "0bf8acf5-7f56-4370-abee-dfc0c3b7d49e"
authors = ["Jherek Healy <jherekhealy@protonmail.com>"]
version = "0.4.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ForwardDiff = "0.10"
julia = "1"
